version: '3'
services:

  collection:
    build: collector/
    dependson:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - "27018:27017"

  etl:
    build: etl/
    links:
    - mongodb
    - postgresdb

  postgresdb:
    image: postgres
    ports:
    - "5565:5432"
